### ISSUE TITLE
CircleSquare.cpp doesn't work

### ISSUE THREAD

**Issue by orestotel** [orestotel/ProjectCPlusPlus#2]
The input is _x_ and _y_ coordinates. There is a circle with radius **1**. The circle is inside a square with side length equal to **2**(because of the radius). 

Task: 
- [The program should check if the coordinate is outside the circle but inside the square. ]

**Comment by whoami-shubham** [comment]
hey! @orestotel  your program doesn't have for coordinates of square and center of the circle . How you going to compare x,y coordinate is inside of square or not ?

**Comment by coder-hellosrikant** [comment]
@whoami-shubham I have solved this issue you can check it here:  https://github.com/coder-hellosrikant/ProjectCPlusPlus/blob/master/CircleSquare.cpp

**Comment by orestotel** [comment]
Awesome! It works properly now. #2 #6 
Pull request approved @coder-hellosrikant
